### ISSUE TITLE
Multiple icons on the same row

### ISSUE THREAD

**Issue by DimiDimit** [Meorge/meorge.github.io#1]
Instead of the icon “card” rows snapping to a size, they should resize as the window grows and shrinks. The class in question is `.card-deck` as seen in the resumé page.

**Comment by DimiDimit** [comment]
It seems that `.card-deck` may not be the best class for this particular case, and a grid should probably be used instead.

**Comment by Meorge** [comment]
Did some looking-into this, this looks like it may be a good example to follow https://codepen.io/JacobLett/pen/yLLdvjV?editors=1100

**Comment by Meorge** [comment]
Fix has been implemented

**Comment by DimiDimit** [comment]
You could use `Closes #X` in the commit title/description to close it automatically and get a “closed this in …” rather than a “closed this” message.
