### ISSUE TITLE
Backdrop filter polyfill

### ISSUE THREAD

**Issue by DimiDimit** [Meorge/meorge.github.io#2]
Certain browsers (most notably Firefox) need a polyfill for the backdrop filter. [backdropjs](https://github.com/AhsanE/backdropjs) is an option.
[Here is the Can I use.](https://caniuse.com/css-backdrop-filter)

**Comment by DimiDimit** [comment]
I tried it and it seems that backdropjs is too buggy and slow, so I guess opacity is the only way to do this. [Modernizr](https://modernizr.com) seems like it could work for this.

**Comment by Meorge** [comment]
I'm going to try something like this first: https://stackoverflow.com/a/44366154/4333479
